# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Generador2.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(649, 531)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.apagadoboton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Poor Richard")
        font.setPointSize(10)
        self.apagadoboton.setFont(font)
        self.apagadoboton.setStyleSheet("background-color: rgb(211, 211, 211);")
        self.apagadoboton.setObjectName("apagadoboton")
        self.gridLayout_3.addWidget(self.apagadoboton, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Poor Richard")
        font.setPointSize(43)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 3)
        self.semiboton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Poor Richard")
        font.setPointSize(10)
        self.semiboton.setFont(font)
        self.semiboton.setStyleSheet("background-color: rgb(211, 211, 211);")
        self.semiboton.setObjectName("semiboton")
        self.gridLayout_3.addWidget(self.semiboton, 2, 2, 1, 1)
        self.manualboton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Poor Richard")
        font.setPointSize(10)
        self.manualboton.setFont(font)
        self.manualboton.setStyleSheet("background-color: rgb(211, 211, 211);")
        self.manualboton.setObjectName("manualboton")
        self.gridLayout_3.addWidget(self.manualboton, 2, 1, 1, 1)
        self.finalboton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Poor Richard")
        font.setPointSize(10)
        self.finalboton.setFont(font)
        self.finalboton.setStyleSheet("background-color: rgb(211, 211, 211);")
        self.finalboton.setObjectName("finalboton")
        self.gridLayout_3.addWidget(self.finalboton, 4, 2, 1, 1)
        self.semiboton2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Poor Richard")
        font.setPointSize(10)
        self.semiboton2.setFont(font)
        self.semiboton2.setStyleSheet("background-color: rgb(211, 211, 211);")
        self.semiboton2.setObjectName("semiboton2")
        self.gridLayout_3.addWidget(self.semiboton2, 4, 0, 1, 1)
        self.autoboton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Poor Richard")
        font.setPointSize(10)
        self.autoboton.setFont(font)
        self.autoboton.setStyleSheet("background-color: rgb(211, 211, 211);")
        self.autoboton.setObjectName("autoboton")
        self.gridLayout_3.addWidget(self.autoboton, 4, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 2, 1, 1)
        self.TEMCICLOS = QtWidgets.QSpinBox(self.centralwidget)
        self.TEMCICLOS.setObjectName("TEMCICLOS")
        self.gridLayout.addWidget(self.TEMCICLOS, 3, 3, 1, 1)
        self.individual = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.individual.setFont(font)
        self.individual.setObjectName("individual")
        self.gridLayout.addWidget(self.individual, 3, 4, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 255, 15);\n"
"border-color: rgb(0, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 5, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 7, 2, 1, 1)
        self.CICLOS = QtWidgets.QSpinBox(self.centralwidget)
        self.CICLOS.setObjectName("CICLOS")
        self.gridLayout.addWidget(self.CICLOS, 3, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 6, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 1, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 1, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 649, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.apagadoboton.setText(_translate("MainWindow", "APAGADO"))
        self.label.setText(_translate("MainWindow", "MANEJO DE SEMAFOROS"))
        self.semiboton.setText(_translate("MainWindow", "SEMI-AUTOMATICO PAR"))
        self.manualboton.setText(_translate("MainWindow", "MANUAL"))
        self.finalboton.setText(_translate("MainWindow", "SALIR"))
        self.semiboton2.setText(_translate("MainWindow", "SEMI-AUTOMATICO INDIVIDUAL"))
        self.autoboton.setText(_translate("MainWindow", "AUTOMATICO"))
        self.individual.setText(_translate("MainWindow", "INDIVIDUAL     "))
        self.pushButton.setText(_translate("MainWindow", "COMENZAR"))
        self.label_3.setText(_translate("MainWindow", "   TIEMPO DE CAMBIO"))
        self.label_2.setText(_translate("MainWindow", "            CICLOS"))


import LogoU_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
